.\" Manpage for bf
.TH man 8 "09 May 2026" "1.0" "bf man page"
.SH NAME
bf \- transpile a bf file
.SH SYNOPSIS
bf [INPUT] [OUTPUT]
.SH DESCRIPTION
bf is a program for compiling brainfuck to valid C code.
.SH OPTIONS
bf doesn't take any options.
.SH SEE ALSO
gcc(1)
.SH BUGS
No known bugs.
.SH AUTHOR
soul
