#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <time.h>
#include <string.h>
#include <assert.h>

#include "file.h"

#define NUM_ELEMENTS 32768 // 2 ^ 15
#define INDENT " "

char* make_indent(int count) {
  size_t len = sizeof(INDENT) * count;

  char* alloc = malloc(len + 1);

  assert(alloc != NULL);

  alloc[0] = '\0';

  for (int i = 0; i < count; i++) {
    strcat(alloc, INDENT);
  }

  return alloc;
}

int indent_level = 0;
void fprint(FILE *fptr, const char *str, int indent_increment) {
  assert(indent_level >= 0);
  if (indent_increment == -1) indent_level--;
  fprintf(fptr, "%s%s", make_indent(indent_level), str);
  if (indent_increment != -1) indent_level += indent_increment;
}

int main(int argc, char **argv)
{
  if (argc < 3) {
    printf("bf: invalid usage.\n");
    printf("Usage: bf <input> <output>");
    return EXIT_FAILURE;
  }
  
  char* ifilename = argv[1];
  char* ofilename = argv[2];
  
  char* file = read_file(ifilename);
  FILE* fptr = open_file(ofilename);
  
  if (file == NULL) {
    fprintf(stderr, "bf: failed to read file.\n");
    return EXIT_FAILURE;
  }
  
  
  fprintf(fptr, "/* this file was automatically generated by bf.c (https://github.com/soulWritesCode/bf.c) at %ld */\n", time(NULL));
  fprintf(fptr, "#include <stdio.h>\n");
  fprintf(fptr, "#include <stdlib.h>\n");
  fprintf(fptr, "\n");
  fprint(fptr, "int main() {\n", 1);
  fprint(fptr, "char *tape = calloc(32768, sizeof(char));\n", 0);
  fprint(fptr, "char *el = tape;\n", 0);

  char *element = file;
  while (*element != '\0') {
    switch (*element) {
      case '>':
        fprint(fptr, "el++;\n", 0);
        break;
      case '<':
        fprint(fptr, "el--;\n", 0);
        break;
      case '-':
        fprint(fptr, "(*el)--;\n", 0);
        break;
      case '+':
        fprint(fptr, "(*el)++;\n", 0);
        break;
      case '.':
        fprint(fptr, "printf(\"%%c\", *el);\n", 0);
        break;
      case ',':
        fprint(fptr, "*el = getchar();\n", 0);
        break;
      case '[':
        fprint(fptr, "while (*el != 0) {\n", 1);
        break;
      case ']':
        fprint(fptr, "}\n", -1);
        break;
    }

    element++;
  }

  fprintf(fptr, "}\n");
  fclose(fptr);
  free(file);

  return 0;

}
