name: Build

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install mingw
      run: sudo apt update && sudo apt install mingw-w64
    - name: make linux
      run: make
    - name: make windows
      run: rm -rf src/*.o && make TARGET=x86_64-bf.exe LDFLAGS=-static CC=x86_64-w64-mingw32-gcc
    - name: Create Release
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        VERSION="v1.0.0-build.${{ github.run_number }}-${GITHUB_SHA::7}"
        gh release create "$VERSION" \
           --title "Release $VERSION" \
           --notes "Automated release for tag ${{ github.ref_name }}" \
           x86_64-bf.exe \
           x86_64-bf-linux
